name: grewal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.20+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  shared_preferences: ^2.0.1
  http: ^0.13.3
  progress_dialog_null_safe: ^1.0.7
  cached_network_image: ^3.1.0
  fluttertoast: ^8.2.2
  page_transition: ^2.0.2
  modal_progress_hud_nsn: ^0.4.0
  pin_code_fields: ^8.0.1
  google_fonts: ^4.0.4
  carousel_slider: ^4.2.1
  connectivity: ^3.0.6
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  razorpay_flutter: ^1.2.7
  multi_select_flutter: ^4.0.0
  servicestack: ^2.0.3
  circular_countdown_timer: ^0.2.0
  fl_chart:
  flutter_slidable: ^3.0.0
  syncfusion_flutter_charts: ^20.4.54
  custom_searchable_dropdown: ^2.0.5
  image_picker: ^1.0.4
  flutter_windowmanager: ^0.2.0
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_animation_progress_bar: ^2.0.1
  mime: ^1.0.4
  flutter_spinkit: ^5.0.0
  syncfusion_flutter_gauges: ^20.4.54
  auto_size_text: ^3.0.0
  youtube_player_flutter: ^8.1.2
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^5.0.0
  wakelock: ^0.6.2
  # package_info_plus: any
  store_redirect: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  screenshot: ^2.1.0
  path_provider: ^2.0.3
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1
  webview_flutter: ^4.4.1
  url_launcher: ^6.0.5
  firebase_analytics: ^10.5.1
  # facebook_app_events: ^0.13.4
  firebase_core: ^2.17.0
  firebase_core_platform_interface: ^4.0.1
  firebase_crashlytics: ^3.3.7
  firebase_crashlytics_platform_interface: ^3.1.2
  badges: ^3.1.2
  # in_app_update: ^2.0.0
  flutter_custom_clippers: ^2.0.0
  provider: ^6.0.0
  rflutter_alert: ^2.0.4
  expandable: ^5.0.1
  file: ^7.0.0
  # package_info_plus_windows: ^2.1.0
  
  # responsive_framework: ^0.1.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_widget_from_html: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  # responsive_framework: ^0.1.4
dependency_overrides:
  platform: ^3.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  image_path_android: "assets/images/app_icon.png"





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/filter.png
    - assets/images/video_icon.png
    - assets/images/hand.png
    - assets/images/credit_card.png
    - assets/images/chat.png
    - assets/images/question.png
    - assets/images/ribbon.png
    - assets/images/ordered_list.png
    - assets/images/performance.png
    - assets/images/support.png
    - assets/images/mcq.png
    - assets/images/medal.png
    - assets/images/badge.png
    - assets/images/up.png
    - assets/images/home_bac.png
    - assets/images/illustration.png
    - assets/images/into_1.png
    - assets/images/intro_2.png
    - assets/images/intro_3.png
    - assets/images/intro_4.png
    - assets/images/thumb_up.png
    - assets/images/thumb_down.png
    - assets/images/out_support.png
    - assets/images/add_photo.png
    - assets/images/play.png
    - assets/images/facebook.png
    - assets/images/youtube.png
    - assets/images/twitter.png
    - assets/images/instagram.png
    - assets/images/whatsapp.png
    - assets/images/telephone.png
    - assets/images/upgrade.png
    - assets/images/tp.png
    - assets/images/2.png
    - assets/images/4.png
    - assets/images/6.png
    - assets/images/8.png
    - assets/images/notify_bell.png
    - assets/images/chemistry.png
    - assets/images/project.png
    - assets/images/lightbulb.png
    - assets/images/problem_solving.png
    - assets/images/account.png
    - assets/images/back.jpeg
    - assets/images/grewal_splash.jpg
    - assets/images/blue_splash.png
    - assets/images/grewal_splash.jpeg
    - assets/images/sample.json
    - assets/
    - assets/youtube.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
